---
# tasks file for sa-ansible-python

  - name: ANSIBLE PYTHON | install python 2
    raw: test -e /usr/bin/python || (apt -qqy update && apt install -qy python-minimal)
    become: yes
    register: python2install

  - name: "FIX: Ubuntu 16.04 LTS doesn't come with certain modules, required by ansible"
    raw: apt-get install python-minimal aptitude -y
    become: true
    become_user: root
    become_method: sudo

  - name: gather facts
    setup:
    when: python2install.changed